version: '3.4'



networks:
  nginx-proxy:
    external: true
  gis-net:
    external: true


volumes:
  vhost:
  html:
  certs:

    
services:


  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:                     
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - nginx-proxy
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html


  http-proxy: # TEST
    image: nginx
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-maps}
      VIRTUAL_PORT: '80'
      VIRTUAL_NETWORK: 'nginx-proxy'
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:-maps}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-info@ciao.com}
    command: "/nginx.sh"
    networks:
      - nginx-proxy
      - gis-net
    volumes:
      - ./proxy.conf:/root/proxy.conf:ro
      - ./nginx.sh:/nginx.sh
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m

  osm: # TEST
    image: dottgonzo/osm-italy:stable
    networks:
      gis-net:
        ipv4_address: 172.99.0.44
    # ports:
    #     - "9090:80"
    volumes: 
      - /cloud/volumes/osm/tiles:/var/lib/mod_tile
      - ./postgresql.conf:/etc/postgresql/10/main/postgresql.conf
      # - ./renderd.conf:/usr/local/etc/renderd.conf
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    command: 'run'
    shm_size: 2G
    logging:
      driver: json-file
      options:
        max-size: 50m


  nominatim:
    image: dottgonzo/nominatim-italy:stale
    restart: always
    networks:
      gis-net:
        ipv4_address: 172.99.0.33
    # ports:
    #     - "8080:8080"
      # volumes:
      #     - /cloud/volumes/nominatim/db:/var/lib/postgresql/12/main
    shm_size: 1gb